apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cinder-demo-vol
  namespace: default
spec:
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: cinder-block-storage
