kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cinder-block-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: cinder.csi.openstack.org
allowVolumeExpansion: true
