# https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta3
apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
nodeRegistration:
  name: $${NODE_NAME}
  kubeletExtraArgs: {}
  ignorePreflightErrors:
    - NumCPU
discovery:
  bootstrapToken:
    token: ${join_token}
    apiServerEndpoint: ${cp_endpoint}:6443
    caCertHashes:
      - "${cert_hash}"
%{ if is_master ~}
controlPlane:
  certificateKey: ${cert_key}
%{~ endif }
