apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-snapshot-data
spec:
  storageClassName: ebs-csi-immediate
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  dataSource:
    name: ebs-csi-volume
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io